# email settings
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'info@trovabiomassa.com'
EMAIL_HOST_PASSWORD = '1openStart2'
EMAIL_PORT = 587

# captcha
RECAPTCHA_PRIVATE_KEY = '6LdoXugSAAAAACixC2adzE9YDzzpJjtdB3P7qECg'
RECAPTCHA_PUBLIC_KEY = '6LdoXugSAAAAAJDUDU9oeQGCuv8yrQ1GQGCPChBF'
